// ============================================
// SIGMA - Exercise Data
// From SIGMA EXOS MONO 2BAC MATHS BIOF
// Chapitre 6: Suites Numeriques
// ============================================

export const EXERCISES = [
  // ====== LEVEL 1: Reconnaissance (Time Attack / MCQ) ======
  {
    id: 'rec-1',
    level: 1,
    type: 'mcq',
    topic: 'reconnaissance',
    difficulty: 1,
    xp: 10,
    timer: 30,
    statement: 'Soit \\( u_n = \\dfrac{n^2 - 1}{n^2 + 1} \\) pour tout \\( n \\in \\mathbb{N} \\). Quelle affirmation est vraie ?',
    options: [
      { text: '\\( (u_n) \\) est croissante', correct: true },
      { text: '\\( (u_n) \\) est convergente', correct: false },
      { text: '\\( (u_n) \\) est arithmetique', correct: false },
    ],
    hint: 'Calcule \\( u_{n+1} - u_n \\) et etudie son signe.',
  },
  {
    id: 'rec-2',
    level: 1,
    type: 'mcq',
    topic: 'reconnaissance',
    difficulty: 1,
    xp: 10,
    timer: 30,
    statement: 'Soit \\( u_n = \\dfrac{n - 2}{n} \\) pour tout \\( n \\in \\mathbb{N}^* \\). Quelle affirmation est vraie ?',
    options: [
      { text: '\\( (u_n) \\) est minoree par \\(-1\\)', correct: false },
      { text: '\\( (u_n) \\) est decroissante', correct: false },
      { text: '\\( (u_n) \\) est convergente', correct: true },
    ],
    hint: 'Calcule la limite de \\( u_n \\) quand \\( n \\to +\\infty \\).',
  },
  {
    id: 'rec-3',
    level: 1,
    type: 'mcq',
    topic: 'reconnaissance',
    difficulty: 1,
    xp: 10,
    timer: 30,
    statement: 'Soit \\( u_n = \\dfrac{1}{2^n - 1} \\) pour tout \\( n \\in \\mathbb{N} \\). Quelle est la nature de \\( (u_n) \\) ?',
    options: [
      { text: '\\( (u_n) \\) est majoree', correct: false },
      { text: '\\( (u_n) \\) est arithmetique', correct: false },
      { text: '\\( (u_n) \\) est geometrique', correct: false },
    ],
    correctIndex: 0,
    hint: 'Verifie si \\( u_n \\) admet un majorant.',
  },
  {
    id: 'rec-4',
    level: 1,
    type: 'mcq',
    topic: 'reconnaissance',
    difficulty: 1,
    xp: 10,
    timer: 30,
    statement: 'Soit \\( u_n = \\left(\\dfrac{2}{5}\\right)^n \\) pour tout \\( n \\in \\mathbb{N} \\). Quelle affirmation est vraie ?',
    options: [
      { text: '\\( (u_n) \\) est majoree', correct: false },
      { text: '\\( (u_n) \\) est arithmetique', correct: false },
      { text: '\\( (u_n) \\) est geometrique', correct: true },
    ],
    hint: 'Calcule \\( \\dfrac{u_{n+1}}{u_n} \\) pour verifier si la suite est geometrique.',
  },
  {
    id: 'rec-5',
    level: 1,
    type: 'mcq',
    topic: 'reconnaissance',
    difficulty: 1,
    xp: 10,
    timer: 30,
    statement: 'Soit \\( u_n = -\\left(\\dfrac{3}{2}\\right)^n \\) pour tout \\( n \\in \\mathbb{N} \\). Quelle affirmation est vraie ?',
    options: [
      { text: '\\( (u_n) \\) est croissante', correct: false },
      { text: '\\( (u_n) \\) est divergente', correct: false },
      { text: '\\( (u_n) \\) est convergente', correct: true },
    ],
    correctIndex: 1,
    hint: 'Quel est la raison? Si \\( |q| > 1 \\), que se passe-t-il?',
  },

  // ====== LEVEL 2: Limites (Dropdown / Guided) ======
  {
    id: 'lim-1',
    level: 2,
    type: 'dropdown',
    topic: 'limites',
    difficulty: 2,
    xp: 20,
    timer: 60,
    statement: 'Calculer \\( \\displaystyle\\lim_{n \\to +\\infty} \\dfrac{n + 5}{n + 1} \\).',
    steps: [
      {
        text: 'On factorise par le terme de plus haut degre au numerateur et au denominateur:',
        blank: 'factoriser_par',
        options: ['\\( n \\)', '\\( n^2 \\)', '\\( 1 \\)'],
        correct: '\\( n \\)',
      },
      {
        text: 'Apres simplification, la limite vaut:',
        blank: 'resultat',
        options: ['\\( 0 \\)', '\\( 1 \\)', '\\( 5 \\)', '\\( +\\infty \\)'],
        correct: '\\( 1 \\)',
      },
    ],
    hint: 'Factorise par \\( n \\) en haut et en bas, puis utilise \\( \\lim \\frac{1}{n} = 0 \\).',
  },
  {
    id: 'lim-2',
    level: 2,
    type: 'dropdown',
    topic: 'limites',
    difficulty: 2,
    xp: 20,
    timer: 60,
    statement: 'Calculer \\( \\displaystyle\\lim_{n \\to +\\infty} (n^2 - \\dfrac{5}{n^6}) \\).',
    steps: [
      {
        text: 'Cette expression est une forme:',
        blank: 'forme',
        options: ['Determinee', 'Indeterminee \\( +\\infty - \\infty \\)', 'Indeterminee \\( \\frac{\\infty}{\\infty} \\)'],
        correct: 'Determinee',
      },
      {
        text: 'La limite est:',
        blank: 'resultat',
        options: ['\\( 0 \\)', '\\( -\\infty \\)', '\\( +\\infty \\)'],
        correct: '\\( +\\infty \\)',
      },
    ],
    hint: '\\( \\lim n^2 = +\\infty \\) et \\( \\lim \\frac{5}{n^6} = 0 \\), donc pas d\'indetermination.',
  },
  {
    id: 'lim-3',
    level: 2,
    type: 'dropdown',
    topic: 'limites',
    difficulty: 2,
    xp: 25,
    timer: 75,
    statement: 'Calculer \\( \\displaystyle\\lim_{n \\to +\\infty} (\\sqrt{n^2 + 1} - n) \\).',
    steps: [
      {
        text: 'C\'est une forme indeterminee du type:',
        blank: 'type_fi',
        options: ['\\( +\\infty - \\infty \\)', '\\( \\frac{\\infty}{\\infty} \\)', '\\( 0 \\times \\infty \\)'],
        correct: '\\( +\\infty - \\infty \\)',
      },
      {
        text: 'Pour lever l\'indetermination, je multiplie par:',
        blank: 'methode',
        options: ['Le conjugue \\( \\frac{\\sqrt{n^2+1}+n}{\\sqrt{n^2+1}+n} \\)', 'Factoriser par \\( n^2 \\)', 'Factoriser par \\( n \\)'],
        correct: 'Le conjugue \\( \\frac{\\sqrt{n^2+1}+n}{\\sqrt{n^2+1}+n} \\)',
      },
      {
        text: 'La limite vaut alors:',
        blank: 'resultat',
        options: ['\\( 0 \\)', '\\( 1 \\)', '\\( +\\infty \\)', '\\( \\frac{1}{2} \\)'],
        correct: '\\( 0 \\)',
      },
    ],
    hint: 'Multiplie par l\'expression conjuguee pour obtenir \\( \\frac{1}{\\sqrt{n^2+1}+n} \\).',
  },
  {
    id: 'lim-4',
    level: 2,
    type: 'dropdown',
    topic: 'limites',
    difficulty: 2,
    xp: 20,
    timer: 60,
    statement: 'Calculer \\( \\displaystyle\\lim_{n \\to +\\infty} (2 \\cdot 3^n + 3) \\).',
    steps: [
      {
        text: 'On sait que \\( \\lim 3^n = \\):',
        blank: 'lim_3n',
        options: ['\\( 0 \\)', '\\( 1 \\)', '\\( +\\infty \\)', '\\( -\\infty \\)'],
        correct: '\\( +\\infty \\)',
      },
      {
        text: 'La limite est donc:',
        blank: 'resultat',
        options: ['\\( 0 \\)', '\\( 3 \\)', '\\( +\\infty \\)', '\\( -\\infty \\)'],
        correct: '\\( +\\infty \\)',
      },
    ],
    hint: 'Car \\( 3 > 1 \\), on a \\( \\lim 3^n = +\\infty \\).',
  },
  {
    id: 'lim-5',
    level: 2,
    type: 'dropdown',
    topic: 'limites',
    difficulty: 3,
    xp: 30,
    timer: 90,
    statement: 'Calculer \\( \\displaystyle\\lim_{n \\to +\\infty} \\dfrac{5^n + 2^n}{5^n - 2^n} \\).',
    steps: [
      {
        text: 'C\'est une forme indeterminee. On factorise par:',
        blank: 'facteur',
        options: ['\\( 2^n \\)', '\\( 5^n \\)', '\\( n \\)'],
        correct: '\\( 5^n \\)',
      },
      {
        text: 'On obtient \\( \\frac{1 + (2/5)^n}{1 - (2/5)^n} \\). Comme \\( |2/5| < 1 \\), on a \\( \\lim (2/5)^n = \\):',
        blank: 'lim_ratio',
        options: ['\\( 0 \\)', '\\( 1 \\)', '\\( +\\infty \\)'],
        correct: '\\( 0 \\)',
      },
      {
        text: 'Donc la limite vaut:',
        blank: 'resultat',
        options: ['\\( 0 \\)', '\\( 1 \\)', '\\( -1 \\)', '\\( 5 \\)'],
        correct: '\\( 1 \\)',
      },
    ],
    hint: 'Factorise par \\( 5^n \\) (le plus grand) en haut et en bas.',
  },

  // ====== LEVEL 3: Recurrence (Drag & Drop) ======
  {
    id: 'rec-dd-1',
    level: 3,
    type: 'dragdrop',
    topic: 'recurrence',
    difficulty: 3,
    xp: 35,
    timer: 120,
    statement: 'Soit \\( (U_n) \\) definie par \\( U_0 = 2 \\) et \\( U_{n+1} = \\frac{U_n}{3} + 2 \\). Montrer par recurrence que \\( \\forall n \\in \\mathbb{N},\\; U_n \\leq 3 \\).',
    steps: [
      'Initialisation: \\( U_0 = 2 \\leq 3 \\) donc \\( P(0) \\) est vraie.',
      'Hypothese de recurrence: supposons que \\( U_n \\leq 3 \\).',
      'Alors \\( \\frac{U_n}{3} \\leq 1 \\) car \\( U_n \\leq 3 \\).',
      'Donc \\( \\frac{U_n}{3} + 2 \\leq 1 + 2 = 3 \\).',
      'C\'est-a-dire \\( U_{n+1} \\leq 3 \\).',
      'Conclusion: par le principe de recurrence, \\( \\forall n \\in \\mathbb{N},\\; U_n \\leq 3 \\).',
    ],
    distractors: [
      'Donc \\( U_n \\geq 3 \\) ce qui est absurde.',
      'On multiplie les deux membres par \\(-1\\).',
    ],
    hint: 'La structure est toujours: Initialisation -> Hypothese -> Heredite -> Conclusion.',
  },
  {
    id: 'rec-dd-2',
    level: 3,
    type: 'dragdrop',
    topic: 'recurrence',
    difficulty: 3,
    xp: 35,
    timer: 120,
    statement: 'Soit \\( (U_n) \\) telle que \\( U_0 = 2 \\) et \\( U_{n+1} = \\frac{2U_n + 1}{U_n} \\). Montrer que \\( U_n \\geq 1 \\) pour tout \\( n \\).',
    steps: [
      'Initialisation: \\( U_0 = 2 \\geq 1 \\), donc la propriete est vraie au rang 0.',
      'Supposons que \\( U_n \\geq 1 \\) pour un certain \\( n \\in \\mathbb{N} \\).',
      'Comme \\( U_n \\geq 1 > 0 \\), on a \\( U_n > 0 \\).',
      'Donc \\( U_{n+1} = 2 + \\frac{1}{U_n} \\geq 2 + 0 = 2 \\geq 1 \\).',
      'L\'heredite est demontree.',
      'Par le principe de recurrence, \\( \\forall n \\in \\mathbb{N},\\; U_n \\geq 1 \\).',
    ],
    distractors: [
      'On pose \\( V_n = U_n - 1 \\) et on montre que \\( V_n \\) est geometrique.',
      'Donc \\( U_n \\to 0 \\) quand \\( n \\to +\\infty \\).',
    ],
    hint: 'N\'oublie pas de verifier que \\( U_n > 0 \\) avant de diviser.',
  },

  // ====== LEVEL 4: Convergence (Mixed) ======
  {
    id: 'conv-1',
    level: 4,
    type: 'mcq',
    topic: 'convergence',
    difficulty: 3,
    xp: 25,
    timer: 45,
    statement: 'Soit \\( (U_n) \\) croissante et majoree par \\( M \\). Que peut-on conclure ?',
    options: [
      { text: '\\( (U_n) \\) est convergente', correct: true },
      { text: '\\( (U_n) \\) est divergente vers \\( +\\infty \\)', correct: false },
      { text: '\\( \\lim U_n = M \\)', correct: false },
    ],
    hint: 'Theoreme fondamental: toute suite croissante et majoree converge.',
  },
  {
    id: 'conv-2',
    level: 4,
    type: 'dropdown',
    topic: 'convergence',
    difficulty: 3,
    xp: 30,
    timer: 90,
    statement: 'Soit \\( (U_n) \\) definie par \\( U_0 = 2 \\) et \\( U_{n+1} = \\frac{U_n}{3} + 2 \\), et \\( V_n = U_n - 3 \\).',
    steps: [
      {
        text: '\\( V_{n+1} = U_{n+1} - 3 = \\frac{U_n}{3} + 2 - 3 = \\frac{U_n - 3}{3} \\). Donc \\( (V_n) \\) est:',
        blank: 'nature',
        options: ['Arithmetique de raison \\( \\frac{1}{3} \\)', 'Geometrique de raison \\( \\frac{1}{3} \\)', 'Ni l\'un ni l\'autre'],
        correct: 'Geometrique de raison \\( \\frac{1}{3} \\)',
      },
      {
        text: '\\( V_0 = U_0 - 3 = -1 \\). Donc \\( V_n = \\):',
        blank: 'vn',
        options: ['\\( -\\left(\\frac{1}{3}\\right)^n \\)', '\\( \\left(\\frac{1}{3}\\right)^n \\)', '\\( -3^n \\)'],
        correct: '\\( -\\left(\\frac{1}{3}\\right)^n \\)',
      },
      {
        text: 'Comme \\( |1/3| < 1 \\), on a \\( \\lim V_n = 0 \\). Donc \\( \\lim U_n = \\):',
        blank: 'lim_un',
        options: ['\\( 0 \\)', '\\( 3 \\)', '\\( +\\infty \\)', '\\( 2 \\)'],
        correct: '\\( 3 \\)',
      },
    ],
    hint: 'Pose \\( V_n = U_n - \\ell \\) ou \\( \\ell \\) est la limite. Montre que \\( (V_n) \\) est geometrique.',
  },

  // ====== LEVEL 5: Suite definie par f(x) ======
  {
    id: 'func-1',
    level: 5,
    type: 'dropdown',
    topic: 'suite_fonction',
    difficulty: 4,
    xp: 40,
    timer: 120,
    statement: 'Soit \\( f(x) = \\dfrac{x^2 + 2}{2x} \\) sur \\( I = [1, \\frac{3}{2}] \\) et \\( U_0 = \\frac{3}{2} \\), \\( U_{n+1} = f(U_n) \\).',
    steps: [
      {
        text: 'Pour montrer que \\( f(I) \\subset I \\), on etudie \\( f \\) sur \\( I \\). \\( f\'(x) = \\):',
        blank: 'derivee',
        options: ['\\( \\frac{x^2 - 2}{2x^2} \\)', '\\( \\frac{2x}{x^2+2} \\)', '\\( \\frac{1}{2} - \\frac{1}{x^2} \\)'],
        correct: '\\( \\frac{x^2 - 2}{2x^2} \\)',
      },
      {
        text: 'Sur \\( [1, \\frac{3}{2}] \\), comme \\( x^2 < 2 \\), \\( f\'(x) \\) est:',
        blank: 'signe',
        options: ['Positive (\\( f \\) croissante)', 'Negative (\\( f \\) decroissante)', 'Change de signe'],
        correct: 'Negative (\\( f \\) decroissante)',
      },
      {
        text: 'Pour trouver \\( \\lim U_n \\), on resout \\( f(x) = x \\), i.e. \\( x^2 + 2 = 2x^2 \\). Donc:',
        blank: 'point_fixe',
        options: ['\\( x = 1 \\)', '\\( x = \\sqrt{2} \\)', '\\( x = 2 \\)'],
        correct: '\\( x = \\sqrt{2} \\)',
      },
    ],
    hint: 'La limite d\'une suite convergente \\( U_{n+1} = f(U_n) \\) est un point fixe de \\( f \\).',
  },

  // ====== LEVEL 6: Examen National (Boss) ======
  {
    id: 'exam-1',
    level: 6,
    type: 'dragdrop',
    topic: 'examen',
    difficulty: 5,
    xp: 50,
    timer: 180,
    statement: 'Examen National: Soit \\( (U_n) \\) definie par \\( U_0 = 2 \\) et \\( U_{n+1} = \\frac{3U_n - 1}{U_n + 1} \\). Montrer que \\( 1 \\leq U_n \\leq 2 \\) pour tout \\( n \\).',
    steps: [
      'Pour \\( n = 0 \\): \\( 1 \\leq U_0 = 2 \\leq 2 \\). L\'initialisation est verifiee.',
      'Supposons que \\( 1 \\leq U_n \\leq 2 \\) pour un certain \\( n \\).',
      'Calculons \\( U_{n+1} - 1 = \\frac{3U_n - 1}{U_n + 1} - 1 = \\frac{2U_n - 2}{U_n + 1} = \\frac{2(U_n - 1)}{U_n + 1} \\).',
      'Comme \\( U_n \\geq 1 \\), on a \\( U_n - 1 \\geq 0 \\) et \\( U_n + 1 > 0 \\), donc \\( U_{n+1} \\geq 1 \\).',
      'Calculons \\( 2 - U_{n+1} = 2 - \\frac{3U_n - 1}{U_n + 1} = \\frac{2U_n + 2 - 3U_n + 1}{U_n + 1} = \\frac{3 - U_n}{U_n + 1} \\).',
      'Comme \\( U_n \\leq 2 < 3 \\), on a \\( 3 - U_n > 0 \\), donc \\( U_{n+1} \\leq 2 \\).',
      'Conclusion: \\( \\forall n \\in \\mathbb{N},\\; 1 \\leq U_n \\leq 2 \\).',
    ],
    distractors: [
      'On pose \\( V_n = U_n^2 \\) pour simplifier.',
      'Comme \\( U_n > 2 \\), on obtient une contradiction.',
      'On applique le theoreme des valeurs intermediaires.',
    ],
    hint: 'Calcule \\( U_{n+1} - 1 \\) et \\( 2 - U_{n+1} \\) separement pour montrer qu\'ils sont positifs.',
  },
];

// Map structure
export const LEVELS = [
  {
    id: 1,
    title: 'Reconnaissance',
    subtitle: 'Identifier les types de suites',
    scoreTarget: '10/20',
    exerciseIds: ['rec-1', 'rec-2', 'rec-3', 'rec-4', 'rec-5'],
  },
  {
    id: 2,
    title: 'Calcul de Limites',
    subtitle: 'Maitriser les techniques de calcul',
    scoreTarget: '12/20',
    exerciseIds: ['lim-1', 'lim-2', 'lim-3', 'lim-4', 'lim-5'],
  },
  {
    id: 3,
    title: 'Raisonnement par Recurrence',
    subtitle: 'Construire une demonstration',
    scoreTarget: '14/20',
    exerciseIds: ['rec-dd-1', 'rec-dd-2'],
  },
  {
    id: 4,
    title: 'Convergence',
    subtitle: 'Suites auxiliaires et criteres',
    scoreTarget: '16/20',
    exerciseIds: ['conv-1', 'conv-2'],
  },
  {
    id: 5,
    title: 'Suite et Fonction',
    subtitle: '\\( U_{n+1} = f(U_n) \\)',
    scoreTarget: '18/20',
    exerciseIds: ['func-1'],
  },
  {
    id: 6,
    title: 'Boss: Examen National',
    subtitle: 'Epreuve chronometree',
    scoreTarget: '20/20',
    exerciseIds: ['exam-1'],
  },
];

export const BADGES = [
  { id: 'first-blood', name: 'Premier Pas', desc: 'Terminer un exercice', icon: '\u{1F476}', condition: (s) => s.totalCompleted >= 1 },
  { id: 'streak-3', name: 'Regulier', desc: '3 jours consecutifs', icon: '\u{1F525}', condition: (s) => s.streak >= 3 },
  { id: 'streak-7', name: 'Flamme Eternelle', desc: '7 jours consecutifs', icon: '\u{1F31F}', condition: (s) => s.streak >= 7 },
  { id: 'perfect-level', name: 'Sans Faute', desc: 'Niveau parfait', icon: '\u{1F4AF}', condition: (s) => s.perfectLevels >= 1 },
  { id: 'speed-demon', name: 'Eclair', desc: 'Exercice en <10s', icon: '\u{26A1}', condition: (s) => s.fastestTime < 10 },
  { id: 'moul-lmaths', name: 'Moul L\'Maths', desc: '10 exercices parfaits', icon: '\u{1F9E0}', condition: (s) => s.perfectExercises >= 10 },
  { id: 'recurrence-king', name: 'Roi de la Recurrence', desc: 'Tous les D&D parfaits', icon: '\u{1F451}', condition: (s) => s.perfectDD >= 4 },
  { id: 'limit-master', name: 'Maitre des Limites', desc: 'Tous les exos limites', icon: '\u{267E}\u{FE0F}', condition: (s) => s.completedLimites >= 5 },
  { id: 'major-promo', name: 'Major de Promo', desc: 'Palier 20/20 atteint', icon: '\u{1F3C6}', condition: (s) => s.highestLevel >= 6 },
];

export const LEADERBOARD = [
  { name: 'Yassine K.', xp: 2450, school: 'Lycee Al Khawarizmi' },
  { name: 'Fatima Z.', xp: 2380, school: 'Lycee Ibn Sina' },
  { name: 'Omar B.', xp: 2210, school: 'Lycee Moulay Ismail' },
  { name: 'Sara M.', xp: 1980, school: 'Lycee Hassan II' },
  { name: 'Ahmed T.', xp: 1870, school: 'Lycee Mohammed V' },
  { name: 'Kenza L.', xp: 1750, school: 'Lycee Al Farabi' },
  { name: 'Hamza R.', xp: 1620, school: 'Lycee Averroes' },
  { name: 'Imane H.', xp: 1540, school: 'Lycee Abi Dar' },
];
